server:
  port: 2333

lavalink:
  server:
    password: "wanmusic123"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true

metrics:
  prometheus:
    enabled: false
